# Generated by Django 3.1.2 on 2020-11-17 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='contact',
            field=models.IntegerField(default=9999999999, verbose_name='Contact No'),
            preserve_default=False,
        ),
    ]
