# Generated by Django 3.1.2 on 2020-11-17 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_form_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='description',
            field=models.TextField(default='found near c-block'),
            preserve_default=False,
        ),
    ]
