# Generated by Django 3.1.2 on 2020-11-17 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_form_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='contact',
            field=models.TextField(verbose_name='Contact No'),
        ),
    ]
