# Generated by Django 3.1.2 on 2020-11-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20201117_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='rollnumber',
            field=models.IntegerField(default=2, verbose_name='Roll number'),
            preserve_default=False,
        ),
    ]
