# Generated by Django 3.1.2 on 2020-11-17 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20201117_2119'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AskHelp',
        ),
    ]
