# Generated by Django 3.1.2 on 2020-11-17 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_askhelp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='askhelp',
            old_name='desribe',
            new_name='describe',
        ),
    ]
