# Generated by Django 3.1.2 on 2021-01-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_classc3_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='classc3',
            name='surname',
            field=models.CharField(default='K', max_length=300),
            preserve_default=False,
        ),
    ]
