# Generated by Django 3.1.2 on 2021-01-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_classc3_surname'),
    ]

    operations = [
        migrations.CreateModel(
            name='college',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='classc3',
            name='address',
            field=models.CharField(default='null', max_length=300),
            preserve_default=False,
        ),
    ]
